apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- with .Values.deck.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: deck
spec:
  rules:
  - host: {{ quote .Values.deck.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: deck
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ quote .Values.deck.ingress.host }}
    secretName: {{ .Values.deck.ingress.host }}