apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-proxy
  labels:
    app: pushgateway-proxy
spec:
  replicas: {{ .Values.pushgateway.proxy.replicas }}
  template:
    metadata:
      labels:
        app: pushgateway-proxy
    spec:
{{- if .Values.pushgateway.proxy.tolerations }}
      tolerations:
{{ toYaml .Values.pushgateway.proxy.tolerations | indent 8 }}
{{- end }}
      containers:
      - name: nginx
        ports:
          - name: http
            containerPort: 8081
        image: {{ .Values.pushgateway.proxy.image }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/
      volumes:
      - name: config-volume
        configMap:
          name: pushgateway-proxy-config